export enum SUCCESS {
  OK = 'OK',
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',
  ACCEPTED = 'ACCEPTED',
  NO_CONTENT = 'NO_CONTENT',
  RESET_CONTENT = 'RESET_CONTENT',
  
}

export enum FAILURE {
  FAILED = 'FAILED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  FAILED_TO_CREATE = 'FAILED_TO_CREATE',
  FAILED_TO_GET = 'FAILED_TO_GET',
  REQUEST_FAILED = 'REQUEST_FAILED',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  NO_DATA = 'NO_DATA',
}

export enum ERROR {
  SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  INVALID_PARAMETERS = 'INVALID_PARAMETERS',
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
  SERVER_ERROR = 'SERVER_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  TIMEOUT = 'TIMEOUT',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  GONE = 'GONE',
}
 

export enum UPLOAD_STATUS
{
  STARTED = 'upload-started',
  PROGRESS = 'upload-progress',
  FAILED = 'FAILED',
  COMPLETED = 'upload-completed',
}
